doctrine:
    dbal:
        url: "%env(resolve:DATABASE_URL)%"

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: "%kernel.debug%"
    orm:
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: "%kernel.project_dir%/src/Entity"
                prefix: 'App\Entity'
                alias: App
        filters:
            user_filter:
                class: App\Repository\Filter\UserFilter
                enabled: true
        dql:
            datetime_functions:
                DAY: DoctrineExtensions\Query\Postgresql\Day
                MONTH: DoctrineExtensions\Query\Postgresql\Month
                YEAR: DoctrineExtensions\Query\Postgresql\Year
                DATEPART: DoctrineExtensions\Query\Postgresql\DatePart
                DATEFORMAT: DoctrineExtensions\Query\Postgresql\DateFormat
                EXTRACT: DoctrineExtensions\Query\Postgresql\ExtractFunction
                DATE: DoctrineExtensions\Query\Postgresql\Date
            string_functions:
                CAST: App\Doctrine\Functions\CastFunction
when@test:
    doctrine:
        dbal:
            connections:
                default:
                    # 'TEST_TOKEN' is typically set by ParaTest
                    dbname_suffix: "_test%env(default::TEST_TOKEN)%"

when@prod:
    doctrine:
        orm:
            auto_mapping: false
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
