# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: "%env(APP_SECRET)%"
    annotations: false
    csrf_protection: true
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        enabled: true
        handler_id: "session.handler.native_file"
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    annotations:
        enabled: false

    enabled_locales: ["en", "nl"]

    #esi: true
    #fragments: true
    php_errors:
        log: true

    http_client:
        scoped_clients:
            seekingalpha.client:
                scope: "https://seekingalpha.com"
                headers:
                    Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8"
                    User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
                    Accept-Encoding: "gzip, deflate, br"
            jsdelivr.client:
                scope: "https://cdn.jsdelivr.net"
                headers:
                    Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8"
                    Accept-Encoding: "gzip, deflate, br"
                    Accept-Language: "en-US,en;q=0.5"
                    Cache-Control: "max-age=0"
                    User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
                    Authorization: "token %env(GITHUB_API_TOKEN)%"
            eu.client:
                scope: "https://www.ecb.europa.eu"
                headers:
                    Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8"
                    Accept-Encoding: "gzip, deflate, br"
                    Accept-Language: "en-US,en;q=0.5"
                    Cache-Control: "max-age=0"
                    User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
