twig:
    file_name_pattern: "*.twig"
    default_path: "%kernel.project_dir%/templates"
    # form_themes: ["bootstrap_5_layout.html.twig"]
    #form_themes: ['themes/form/my_theme.html.twig']
    form_themes:
        - "tailwind_2_layout.html.twig"
        - "themes/form/my_theme.html.twig"


when@test:
    twig:
        strict_variables: true
