stages:
  - analysis
  - test
  - deployment

default:
  image: phpdockerio/php:8.3-fpm
  services:
    - name: postgres:16-alpine
      alias: postgresql

cache:
  key: ${CI_COMMIT_REF_SLUG}
  policy: pull
  paths:
    - vendor/
    - node_modules/

variables:
  POSTGRES_DB: theapplication
  POSTGRES_USER: theapplication
  POSTGRES_PASSWORD: theapplication
  DATABASE_URL: 'postgresql://theapplication:theapplication@postgresql:5432/theapplication?serverVersion=16&charset=utf8'
  TEST_DATABASE_PORT: 5432
  TEST_DATABASE_HOST: postgresql
  GITHUB_API_TOKEN: "thisismysecrettoken"

static_analysis:
  stage: analysis
  script:
    - bash ci/php-install.sh
    - php composer.phar require --dev phpstan/phpstan
    - php vendor/bin/phpstan.phar analyse src --level=1

phpunit:
  stage: test
  script:
    - bash ci/php-install.sh
    - php composer.phar install -o
    - php composer.phar require --dev symfony/phpunit-bridge
    - php bin/console tailwind:build
    - php bin/console asset-map:compile --no-debug
    - sh ci/php_test_run.sh
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull-push
    paths:
      - node_modules

deployment:
  stage: deployment
  environment:
    name: staging
    url: http://example.com
  script:
    - sh ci/git-install.sh
  when: manual
