printWidth: 80
tabWidth: 4
semi: false
useTabs: true
singleQuote: true
twigSingleQuote: true
twigMultiTags:
  - "nav,endnav"
  - "switch,case,default,endswitch"
  - "ifchildren,endifchildren"
  - "cache,endcache"
  - "js,endjs"
plugins:
  - "@prettier/plugin-php"
  - "prettier-plugin-tailwindcss"
  - "@zackad/prettier-plugin-twig"
