printWidth: 80
tabWidth: 4
plugins:
  - "@prettier/plugin-php"
trailingComma: "es5"
semi: true
singleQuote: true
requireConfig: true
bracketSpacing: true
bracketSameLine: false
jsxBracketSameLine: false
singleAttributePerLine: true
