###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: dividend-memcached

    mailhog:
      image: mailhog/mailhog:latest
      container_name: dividend-mailhog
      ports:
        - "9001:8025"

    redis:
      image: redis:alpine
      container_name: dividend-redis

    mariadb:
      image: mariadb:10.5
      hostname: dbserver
      restart: always
      container_name: dividend-mariadb
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/mysql/mariadb.cnf:/etc/mysql/mariadb.cnf
        - ../data/mysql:/var/lib/mysql
        - ../logs/mysql:/var/log/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=hd9251zp
        - MYSQL_DATABASE=dividend
        - MYSQL_USER=dividend
        - MYSQL_PASSWORD=dividend
      ports:
        - 3306:3306

    webserver:
      image: nginx:alpine
      restart: always
      container_name: dividend-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"
       - "443:443"
      links:
        - php-fpm

    php-fpm:
      build: phpdocker/php-fpm
      restart: always
      container_name: dividend-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
      depends_on:
        - mariadb
      links:
        - mariadb:mariadb 
      external_links:
        - mariadb:mariadb
