<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250723142320 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE corporate_action (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, event_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ratio DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, position_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8F0B005EDD842E46 ON corporate_action (position_id)');
        $this->addSql('ALTER TABLE corporate_action ADD CONSTRAINT FK_8F0B005EDD842E46 FOREIGN KEY (position_id) REFERENCES position (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE corporate_action DROP CONSTRAINT FK_8F0B005EDD842E46');
        $this->addSql('DROP TABLE corporate_action');
    }
}
