<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250509163458 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE trading212_pie_instrument (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ticker_name VARCHAR(255) NOT NULL, owned_quantity DOUBLE PRECISION NOT NULL, price_avg_invested_value DOUBLE PRECISION NOT NULL, price_avg_value DOUBLE PRECISION NOT NULL, price_avg_result DOUBLE PRECISION NOT NULL, raw JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            DROP TABLE trading212_pie_instrument
        SQL);
    }
}
