<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250503155701 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE incomes_shares_data (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ticker_id INT NOT NULL, position_id INT NOT NULL,price DOUBLE PRECISION NOT NULL, profit_loss DOUBLE PRECISION NOT NULL, allocation DOUBLE PRECISION NOT NULL, amount DOUBLE PRECISION NOT NULL, distributions DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_9B3BEAC8556B180E ON incomes_shares_data (ticker_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_9B3BEAC8DD842E46 ON incomes_shares_data (position_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE incomes_shares_data ADD CONSTRAINT FK_9B3BEAC8556B180E FOREIGN KEY (ticker_id) REFERENCES ticker (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE incomes_shares_data ADD CONSTRAINT FK_9B3BEAC8DD842E46 FOREIGN KEY (position_id) REFERENCES position (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE transaction ALTER profit TYPE DOUBLE PRECISION
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE incomes_shares_data DROP CONSTRAINT FK_9B3BEAC8556B180E
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE incomes_shares_data DROP CONSTRAINT FK_9B3BEAC8DD842E46
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE incomes_shares_data
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE transaction ALTER profit TYPE DOUBLE PRECISION
        SQL);
    }
}
