<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250510170816 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE ticker_alternative_symbol (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                symbol VARCHAR(255) NOT NULL,
                ticker_id INT NOT NULL, PRIMARY KEY(id),
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_A7F2AEDA556B180E ON ticker_alternative_symbol (ticker_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE ticker_alternative_symbol ADD CONSTRAINT FK_A7F2AEDA556B180E FOREIGN KEY (ticker_id) REFERENCES ticker (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE ticker_alternative_symbol DROP CONSTRAINT FK_A7F2AEDA556B180E
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE ticker_alternative_symbol
        SQL);
    }
}
