<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250504140510 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE incomes_shares_data_set (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, total_profit_loss DOUBLE PRECISION NOT NULL, total_distribution DOUBLE PRECISION NOT NULL, total_allocation DOUBLE PRECISION NOT NULL, yield DOUBLE PRECISION NOT NULL, uuid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE incomes_shares_data ADD dataset UUID DEFAULT NULL
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            DROP TABLE incomes_shares_data_set
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE incomes_shares_data DROP dataset
        SQL);
    }
}
