<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250508125938 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE api_key (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                api_key VARCHAR(255) NOT NULL,
                user_id INT DEFAULT NULL,
                api_key_name_id INT NOT NULL, PRIMARY KEY(id),
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL
                )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_C912ED9DA76ED395 ON api_key (user_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_C912ED9D79B63266 ON api_key (api_key_name_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE api_key_name (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                key_name VARCHAR(255) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id)
                )
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE api_key ADD CONSTRAINT FK_C912ED9DA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE api_key ADD CONSTRAINT FK_C912ED9D79B63266 FOREIGN KEY (api_key_name_id) REFERENCES api_key_name (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE api_key DROP CONSTRAINT FK_C912ED9DA76ED395
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE api_key DROP CONSTRAINT FK_C912ED9D79B63266
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE api_key
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE api_key_name
        SQL);
    }
}
