<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250304134552 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE monthly_summary (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ac_date DATE NOT NULL, deposit_withdrawal DOUBLE PRECISION DEFAULT 0 NOT NULL, closed_position_result DOUBLE PRECISION DEFAULT 0 NOT NULL, dividends DOUBLE PRECISION DEFAULT 0 NOT NULL, interest_on_uninvested_cash DOUBLE PRECISION DEFAULT 0 NOT NULL, commissions_and_fees DOUBLE PRECISION DEFAULT 0 NOT NULL, equity_charges_and_fees DOUBLE PRECISION DEFAULT 0 NOT NULL, account_adjustments DOUBLE PRECISION DEFAULT 0 NOT NULL, account_value DOUBLE PRECISION DEFAULT 0 NOT NULL, cash DOUBLE PRECISION DEFAULT 0 NOT NULL, bonus_non_withdrawable DOUBLE PRECISION DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, uuid UUID NOT NULL, PRIMARY KEY(id))');

    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE monthly_summary');

    }
}
